# Generated by Django 5.2.13 on 2026-04-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier for this policy setting', max_length=100, unique=True)),
                ('setting_type', models.CharField(choices=[('tuition_cap', 'Tuition Cap'), ('living_allowance', 'Living Allowance'), ('credential_amount', 'Credential Amount'), ('deadline', 'Deadline'), ('budget_cap', 'Budget Cap')], help_text='Type of policy setting', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Numeric value for this setting', max_digits=12)),
                ('stream', models.CharField(blank=True, choices=[('PSSSP', 'Post-Secondary Student Support Program'), ('UCEPP', 'Upgrading and Community Education Partnership Program'), ('DGGR', "Délı̨nę Got'ı̨nę Government Resources"), ('C-DFN', 'Délı̨nę First Nation PSSSP')], help_text='Funding stream (if applicable)', max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('FT', 'Full-Time'), ('PT', 'Part-Time')], help_text='Enrollment status (FT/PT, if applicable)', max_length=2, null=True)),
                ('dependent_count', models.IntegerField(blank=True, help_text='Number of dependents (if applicable)', null=True)),
                ('credential_type', models.CharField(blank=True, help_text='Credential type for graduation awards', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of this policy setting')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy Setting',
                'verbose_name_plural': 'Policy Settings',
                'db_table': 'api_policysetting',
                'ordering': ['key'],
            },
        ),
    ]
