# Generated by Django 5.2.13 on 2026-04-18 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_policysetting_model'),
        ('forms', '0005_formsubmission_amount_formsubmission_decided_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('tuition', 'Tuition Payment'), ('living_allowance', 'Living Allowance'), ('graduation_award', 'Graduation Award'), ('travel_claim', 'Travel Claim'), ('practicum_award', 'Practicum Award'), ('graduation_travel_bursary', 'Graduation Travel Bursary')], help_text='Type of payment being disbursed', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in CAD', max_digits=12)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current payment status', max_length=20)),
                ('scheduled_date', models.DateField(help_text='Date payment is scheduled for')),
                ('processed_date', models.DateField(blank=True, help_text='Date payment was actually processed', null=True)),
                ('reference_number', models.CharField(help_text='Unique payment reference number (PAY-YYYY-XXXXXX)', max_length=50, unique=True)),
                ('finance_notes', models.TextField(blank=True, help_text='Internal notes for Finance staff', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student receiving the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(help_text='Link to the approved form submission', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='forms.formsubmission')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'api_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
