# Generated by Django 5.2.13 on 2026-04-18 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_payment_model'),
        ('forms', '0005_formsubmission_amount_formsubmission_decided_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar_email', models.EmailField(help_text='Email address of the institution registrar', max_length=254)),
                ('institution_name', models.CharField(help_text='Name of the educational institution', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Registrar'), ('submitted', 'Form B Submitted'), ('verified', 'Enrollment Verified'), ('overdue', 'Overdue'), ('expired', 'Expired')], default='pending', help_text='Current status of Form B tracking', max_length=20)),
                ('sent_date', models.DateTimeField(blank=True, help_text='Date Form B was sent to registrar', null=True)),
                ('due_date', models.DateField(help_text='Date Form B response is due (30 days from submission)')),
                ('submitted_date', models.DateField(blank=True, help_text='Date Form B was submitted by registrar', null=True)),
                ('verification_date', models.DateField(blank=True, help_text='Date enrollment was verified', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about Form B status', null=True)),
                ('reminder_count', models.IntegerField(default=0, help_text='Number of reminders sent to registrar')),
                ('last_reminder_sent', models.DateTimeField(blank=True, help_text='Date of last reminder sent to registrar', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_a_submission', models.OneToOneField(help_text='Link to the Form A submission', on_delete=django.db.models.deletion.CASCADE, related_name='form_b_tracking', to='forms.formsubmission')),
            ],
            options={
                'verbose_name': 'Form B Tracking',
                'verbose_name_plural': 'Form B Tracking Records',
                'db_table': 'api_formbtracking',
                'ordering': ['-created_at'],
            },
        ),
    ]
