# Generated by Django 5.2.13 on 2026-04-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_formbtracking_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraTuitionBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(help_text='Fiscal year in format YYYY-YYYY (e.g., 2024-2025)', max_length=10, unique=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default=36000.0, help_text='Total annual budget cap for DGGR extra tuition', max_digits=12)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount already allocated to students', max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=36000.0, help_text='Remaining budget available for allocation', max_digits=12)),
                ('allocation_count', models.IntegerField(default=0, help_text='Number of students funded in this fiscal year')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about budget status or allocations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extra Tuition Budget',
                'verbose_name_plural': 'Extra Tuition Budgets',
                'db_table': 'api_extratuitionbudget',
                'ordering': ['-fiscal_year'],
            },
        ),
    ]
