# Generated by Django 5.2.13 on 2026-04-18 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_extratuitionbudget_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='First day of the disbursement month (YYYY-MM-01)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monthly disbursement amount in CAD', max_digits=12)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of this monthly disbursement', max_length=20)),
                ('processed_date', models.DateField(blank=True, help_text='Date this monthly payment was actually processed', null=True)),
                ('finance_reference', models.CharField(blank=True, help_text='Finance system reference number for this disbursement', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this monthly disbursement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(help_text='Link to the parent Payment record', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='api.payment')),
            ],
            options={
                'verbose_name': 'Payment Schedule',
                'verbose_name_plural': 'Payment Schedules',
                'db_table': 'api_paymentschedule',
                'ordering': ['month_year'],
                'unique_together': {('payment', 'month_year')},
            },
        ),
    ]
