# Generated by Django 5.2.13 on 2026-04-20 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_enrollment_status_profile_institute_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policysetting',
            name='category',
            field=models.CharField(blank=True, help_text='Grouping category for the dashboard (e.g., psssp_tuition)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policysetting',
            name='field_key',
            field=models.CharField(blank=True, help_text='Technical key within the category (e.g., max_per_semester)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policysetting',
            name='field_label',
            field=models.CharField(blank=True, help_text='Human-readable label for the setting', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='policysetting',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policysetting',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measurement (e.g., $, days, months)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policysetting',
            name='value',
            field=models.CharField(help_text='Value for this setting (stored as string for flexibility)', max_length=255),
        ),
    ]
