# Generated by Django 5.2.13 on 2026-04-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile_account_holder_name_profile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='primary_stream',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
