# Generated by Django 5.2.13 on 2026-04-16 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_institute_profile_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('review', 'Review'), ('pending', 'Pending Director'), ('approved', 'Approved'), ('denied', 'Denied'), ('waitingb', 'Waiting Form B'), ('more_info_required', 'More Info Required')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='ShareableLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='api.application')),
            ],
        ),
    ]
