# Generated by Django 5.2.13 on 2026-04-18 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_application_status_shareablelink'),
        ('forms', '0006_formsubmission_office_use_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareablelink',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='forms.formsubmission'),
        ),
        migrations.AlterField(
            model_name='shareablelink',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='api.application'),
        ),
    ]
