# Generated by Django 5.2.13 on 2026-04-18 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_shareablelink_submission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='policysetting',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='policysetting',
            name='field_key',
            field=models.CharField(default='legacy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policysetting',
            name='field_label',
            field=models.CharField(default='legacy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policysetting',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policysetting',
            name='section',
            field=models.CharField(default='legacy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policysetting',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='policysetting',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policysetting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='policysetting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='policysetting',
            name='data',
        ),
        migrations.RemoveField(
            model_name='policysetting',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='policysetting',
            unique_together={('section', 'field_key')},
        ),
    ]
