# Generated by Django 5.2.13 on 2026-04-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_updated_at_policysetting_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policysetting',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
