# Generated by Django 5.2.13 on 2026-04-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_formsubmission_amount_formsubmission_decided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='office_use_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
