# Generated by Django 5.2.13 on 2026-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_formsubmission_amount_formsubmission_decided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='decision_letter_text',
            field=models.TextField(blank=True, help_text='Auto-generated approval/rejection letter', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='director_exception_approved',
            field=models.BooleanField(default=False, help_text='Director approval for late submission'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='escalation_level',
            field=models.CharField(choices=[('none', 'None'), ('director', 'Director'), ('beneficiary_services', 'Beneficiary Services'), ('ceo', 'CEO'), ('dkdk', 'DKDK')], default='none', help_text='Appeal escalation level for FormH submissions', max_length=20),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='guardian_consent_on_file',
            field=models.BooleanField(default=False, help_text='Guardian consent flag for students under 18'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='is_late',
            field=models.BooleanField(default=False, help_text='Indicates submission is past semester deadline'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='overpayment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated overpayment for status changes', max_digits=12),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='program_stream',
            field=models.CharField(blank=True, choices=[('psssp', 'PSSSP'), ('ucepp', 'UCEPP'), ('dggr', 'DGGR'), ('c-dfn', 'C-DFN')], help_text='Funding stream: PSSSP, UCEPP, DGGR, or C-DFN', max_length=10, null=True),
        ),
    ]
